pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Hemant9766/proj-CICD_01.git',
                branch: 'master'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t your-image-name:latest -f python-jenkins-argocd-k8s/Dockerfile python-jenkins-argocd-k8s/


                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push hemant9766/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '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', 
                url: 'https://github.com/Hemant9766/cicd_deployment-file.git',
                branch: 'master'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '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', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/Hemant9766/cicd_deployment-file.git HEAD:master
                        '''                        
                    }
                }
            }
        }
    }
}
